### ISSUE TITLE
New Raspberry Pi 2 / MPR121 / OS - simpletest.py fails

### ISSUE THREAD

**Issue by larkintuckerllc** [adafruit/Adafruit_Python_MPR121#5]
Followed instructions with no issue for getting the MPR121 operational until I get error when running simpletest.py.

HW: Raspberry Pi 2 Model B V1.1
HAT: MPR121
OS: Raspbian: Linux raspberrypi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux

OUTPUT:
pi@raspberrypi:~/Adafruit_Python_MPR121/examples $ sudo python simpletest.py 
Adafruit MPR121 Capacitive Touch Sensor Test
chmod: cannot access ‘/sys/module/i2c_bcm2708/parameters/combined’: No such file or directory
Traceback (most recent call last):
  File "simpletest.py", line 34, in <module>
    if not cap.begin():
  File "build/bdist.linux-armv7l/egg/Adafruit_MPR121/MPR121.py", line 90, in begin
  File "build/bdist.linux-armv7l/egg/Adafruit_GPIO/I2C.py", line 81, in require_repeated_start
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'chmod 666 /sys/module/i2c_bcm2708/parameters/combined' returned non-zero exit status 1

**Comment by larkintuckerllc** [comment]
Ok, when I Googled i2c, I figured out what I was missing (likely a difference between using the MPR121 and the external module).  The key was to activate i2c in the kernel.  Documented at https://learn.adafruit.com/adafruits-raspberry-pi-lesson-4-gpio-setup/configuring-i2c.
